// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: cache.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoCache_Get_FullMethodName    = "/pb.GoCache/Get"
	GoCache_Put_FullMethodName    = "/pb.GoCache/Put"
	GoCache_Delete_FullMethodName = "/pb.GoCache/Delete"
)

// GoCacheClient is the client API for GoCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoCacheClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error)
	Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error)
}

type goCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewGoCacheClient(cc grpc.ClientConnInterface) GoCacheClient {
	return &goCacheClient{cc}
}

func (c *goCacheClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, GoCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCacheClient) Put(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForGet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForGet)
	err := c.cc.Invoke(ctx, GoCache_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goCacheClient) Delete(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ResponseForDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseForDelete)
	err := c.cc.Invoke(ctx, GoCache_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoCacheServer is the server API for GoCache service.
// All implementations must embed UnimplementedGoCacheServer
// for forward compatibility.
type GoCacheServer interface {
	Get(context.Context, *Request) (*ResponseForGet, error)
	Put(context.Context, *Request) (*ResponseForGet, error)
	Delete(context.Context, *Request) (*ResponseForDelete, error)
	mustEmbedUnimplementedGoCacheServer()
}

// UnimplementedGoCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoCacheServer struct{}

func (UnimplementedGoCacheServer) Get(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGoCacheServer) Put(context.Context, *Request) (*ResponseForGet, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedGoCacheServer) Delete(context.Context, *Request) (*ResponseForDelete, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGoCacheServer) mustEmbedUnimplementedGoCacheServer() {}
func (UnimplementedGoCacheServer) testEmbeddedByValue()                 {}

// UnsafeGoCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoCacheServer will
// result in compilation errors.
type UnsafeGoCacheServer interface {
	mustEmbedUnimplementedGoCacheServer()
}

func RegisterGoCacheServer(s grpc.ServiceRegistrar, srv GoCacheServer) {
	// If the following call panics, it indicates UnimplementedGoCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoCache_ServiceDesc, srv)
}

func _GoCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCacheServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCache_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCacheServer).Put(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoCache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCache_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCacheServer).Delete(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GoCache_ServiceDesc is the grpc.ServiceDesc for GoCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GoCache",
	HandlerType: (*GoCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GoCache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _GoCache_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GoCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}
